### ISSUE TITLE
Search by Lyrics

### ISSUE THREAD

**Issue by Khennjo** [sidadventist/sid_hymnal#29]
Search by Hymn Number or Option to go directly to Hymn Number

**Comment by Khennjo** [comment]
Maybe 3 options to search - Lyrics, Song Title and Both

**Comment by nadchif** [comment]
> Search by Hymn Number or Option to go directly to Hymn Number

@Khennjo Thank you for this valuable feedback.

Search by Hymn Number is already available. 
iOS: You can enter the number directly in the search box.
For Android: You can use search by number or the JumpTo keypad.
