### ISSUE TITLE
Song Number should match actual Adventist Hymnal number

### ISSUE THREAD

**Issue by Khennjo** [sidadventist/sid_hymnal#30]
Song Numbers should match actual Adventist Hymnal numbers

**Comment by dubehimself** [comment]
It depends on which Hymnal is being followed. If we are basing on _Christ in Song_, the Song numbers are correct and they do match.

**Comment by Khennjo** [comment]
I guess i came from the side of the world where Adventist Hymnal is widely used. But I also noticed that many churches around Pretoria also use Adventist Hymnal. So coming from that user base, can there be 2 sets of hymn number arrangements? 1 based in Christ in Song and the other for Adventist Hymnal. This can probably be done by tagging a song with both hymn number and allow search based on the hymnal version.

**Comment by sangronism** [comment]
I agree with Ken, Song Numbers should match actual Adventist Hymnal numbers. Probably having 2 sets of hymn number arrangement can be tricky but I guess Daniel can explore if this is possible

**Comment by nadchif** [comment]
The idea behind using _Christ in Song_ as the standard, is because it is the most widely translated Hymnal across SID (AFAIK). I know there's Zulu, Tswana, Xhosa, Shona, Tonga, Chewa, Sotho, Swahili other versions. 

Maybe we could think of an implementation where we can offer users the chance to use the AH numbering as an option, but still use CIS as the standard. What do you think? Open and welcome to your feedback

**Comment by sangronism** [comment]
Good point Daniel. And because our priority are our territory languages let's go ahead with your idea

**Comment by Khennjo** [comment]
The idea i have in mind is that - for example Hymn #1 in CIS is Watchmen, Blow the Gospel Trumpet but in SDA Hymnal, it is #368. 

So we tag Watchmen... with both 1 and 368 and we can have a sorting for CIS to display the list based on CIS and a sorting display based of SDA Hymnal. The rest that are unique to each set can be displayed at the bottom of the list.

Not sure how easy or difficult this would be to implement.

**Comment by Khennjo** [comment]
The rest of the languages can also be sorted the same way

**Comment by thembimoyo2020** [comment]
Or we can have AH as a  stand alonee Hymnal.

**Comment by nadchif** [comment]
What do you think about an implementation like this: 

Hymn View: 
iOS
![cis_ios_hymn](https://user-images.githubusercontent.com/47924887/76450939-4b42aa00-63d7-11ea-9462-0029a908d9c4.png)
Android
![cis_android_hymn](https://user-images.githubusercontent.com/47924887/76451192-bbe9c680-63d7-11ea-8f19-f7d67b66f159.png)


Search View:
![cis_ios_search](https://user-images.githubusercontent.com/47924887/76450957-54cc1200-63d7-11ea-808f-7591d2266665.png)

A search done using AH number:
![cis_ios_searched](https://user-images.githubusercontent.com/47924887/76450985-631a2e00-63d7-11ea-810b-d37103ec7db8.png)

This would provide the option @Khennjo is talking about.

We could then go further to offer users to choose to use the full AH hymnal as default English version. Something like this: 
![cis_android_settings](https://user-images.githubusercontent.com/47924887/76451183-b5f3e580-63d7-11ea-8d4b-1de9a65d13e8.png)

What do you think?

**Comment by Khennjo** [comment]
> What do you think about an implementation like this:
> 
> Hymn View:
> iOS
> ![cis_ios_hymn](https://user-images.githubusercontent.com/47924887/76450939-4b42aa00-63d7-11ea-9462-0029a908d9c4.png)
> Android
> ![cis_android_hymn](https://user-images.githubusercontent.com/47924887/76451192-bbe9c680-63d7-11ea-8f19-f7d67b66f159.png)
> 
> Search View:
> ![cis_ios_search](https://user-images.githubusercontent.com/47924887/76450957-54cc1200-63d7-11ea-808f-7591d2266665.png)
> 
> A search done using AH number:
> ![cis_ios_searched](https://user-images.githubusercontent.com/47924887/76450985-631a2e00-63d7-11ea-810b-d37103ec7db8.png)
> 
> This would provide the option @Khennjo is talking about.
> 
> We could then go further to offer users to choose to use the full AH hymnal as default English version. Something like this:
> ![cis_android_settings](https://user-images.githubusercontent.com/47924887/76451183-b5f3e580-63d7-11ea-8d4b-1de9a65d13e8.png)
> 
> What do you think?

This should work well!

**Comment by nadchif** [comment]
I've opened a separate issue to address the first part of this implementation: Adding the Adventist Hymnal number equivalent.

I think we can also leave this issue open till we also implement the second part: Adding the complete Adventist Hymnal to the app.
