### ISSUE TITLE
Add corresponding Adventist Hymn numbers

### ISSUE THREAD

**Issue by nadchif** [sidadventist/sid_hymnal#39]
This issue is part of the solution for https://github.com/sidadventist/sid_hymnal/issues/30. 

It is very straight-forward and clear for anyone willing to help. We need to add a matching Advent Hymnal Number where available in Christ in song. 

The file you will be working on is [/assets/cis-ah.json](https://github.com/sidadventist/sid_hymnal/blob/master/assets/cis-ah.json). 

The structure is in [JSON](https://www.w3schools.com/js/js_json_intro.asp) Format. Simple put it is as follows:[ 
```
{
    "1":"368",
    "3":"206",
    "4":"442",
    "6":"598",
    "7":"218",
    "8":"216"
}
```
1. On the left hand side of the colon you put the `Christ in Song` Hymn number, in quotes
2. On the right hand side of the colon you put the `Advent Hymnal` number, in quotes as well
3. You add a comma before new number pair.

You can [edit the file](https://github.com/sidadventist/sid_hymnal/edit/master/assets/cis-ah.json) directly in the browser, or you can [manually fork the repo](https://guides.github.com/activities/forking/), clone it to your computer and work on it.

**Comment by dubehimself** [comment]
**Clarification requested:**

By AH do we mean Advent Hymns?

![2020_03_13 13_35 Office Lens](https://user-images.githubusercontent.com/6096228/76617823-c3bc7e80-652f-11ea-98bf-8baa42837b7f.jpg)

**Comment by nadchif** [comment]
Sorry, I've been using AH as SDA Hymnal. I think it's SDA Hymnal.  Based on the example @Khennjo provided here

**Comment by Khennjo** [comment]
> This issue is part of the solution for #30.
> 
> It is very straight-forward and clear for anyone willing to help. We need to add a matching Adventist Hymn Number where available in Christ in song.
> 
> The file you will be working on is [/assets/cis-ah.json](https://github.com/sidadventist/sid_hymnal/blob/master/assets/cis-ah.json).
> 
> The structure is in [JSON](https://www.w3schools.com/js/js_json_intro.asp) Format. Simple put it is as follows:[
> 
> ```
> {
>     "1":"368",
>     "3":"206",
>     "4":"442",
>     "6":"598",
>     "7":"218",
>     "8":"216"
> }
> ```
> 
> 1. On the left hand side of the colon you put the `Christ in Song` Hymn number, in quotes
> 2. On the right hand side of the colon you put the `Adventist Hymnal` number, in quotes as well
> 3. You add a comma before new number pair.
> 
> You can [edit the file](https://github.com/sidadventist/sid_hymnal/edit/master/assets/cis-ah.json) directly in the browser, or you can [manually fork the repo](https://guides.github.com/activities/forking/), clone it to your computer and work on it.

I can help on this next week when Im back in the office.

**Comment by nadchif** [comment]
@Khennjo thank you. That would be great 😄

**Comment by dubehimself** [comment]
> Sorry, I've been using AH as SDA Hymnal. I think it's SDA Hymnal. Based on the example @Khennjo provided here [#30 (comment)](https://github.com/sidadventist/sid_hymnal/issues/30#issuecomment-597651404)

That's fine. I had started but I was basing on Advent Hymns, which is what I have seen used in the churches that I have been to around Zimbabwe.

Seeing that Advent Hymns is also an official Hymnal of the Seventh-day Adventist Church, I don't see any harm in adding a reference to it. Any thoughts?

**Comment by nadchif** [comment]
@dubehimself perhaps you can continue working on  [/assets/cis-ah.json](https://github.com/sidadventist/sid_hymnal/blob/master/assets/cis-ah.json) and match the hymns to `Advent Hymn`.

I will add a new file to the project `/assets/cis-sda.json` and @Khennjo could help us do the CIS to SDA Hymnal in that file.
