### ISSUE TITLE
Dark mode issues 

### ISSUE THREAD

**Issue by thembimoyo2020** [sidadventist/sid_hymnal#40]
Have a look at what the dark mode looks like... 
![0F34EB48-64DD-47C7-9726-A0FA5F87FF66](https://user-images.githubusercontent.com/60009600/76488786-c8494000-6426-11ea-9df6-0e2025f3f714.png)
![2F72AC3A-E561-444C-8E30-43CED8D0D66E](https://user-images.githubusercontent.com/60009600/76488792-cc755d80-6426-11ea-9aea-1948b848ffbe.png)

**Comment by nadchif** [comment]
This issue will be further addressed here https://github.com/sidadventist/sid_hymnal/issues/42
